import Mathlib.GroupTheory.Coxeter.Basic
import Mathlib.GroupTheory.Perm.Sign
import Mathlib.GroupTheory.Perm.ViaEmbedding
import Mathlib.Tactic

/-!
# Extending adjacent-transposition operators

This file constructs the type-A symmetric-group presentation from its adjacent generators.
All auxiliary normal-form statements are theorems about arbitrary monoids; no presentation
completeness assumption is made.
-/

namespace Bridge.Young.CoxeterExtension

section NormalForm

variable {G : Type*} [Monoid G]

/-- The usual adjacent-transposition relations, with natural-number indices below `n`. -/
structure Relations (n : ℕ) (s : ℕ → G) : Prop where
  square : ∀ i, i < n → s i * s i = 1
  distant : ∀ i j, i < n → j < n → i + 1 < j → s i * s j = s j * s i
  braid : ∀ i, i + 1 < n → s i * s (i+1) * s i = s (i+1) * s i * s (i+1)

/-- The descending string `s (j+k-1) ⋯ s j`; its rightmost factor acts first. -/
def down (s : ℕ → G) (j : ℕ) : ℕ → G
  | 0 => 1
  | k+1 => down s (j+1) k * s j

@[simp] theorem down_zero (s : ℕ → G) (j : ℕ) : down s j 0 = 1 := rfl
@[simp] theorem down_succ (s : ℕ → G) (j k : ℕ) :
    down s j (k+1) = down s (j+1) k * s j := rfl

theorem down_commute_below {n : ℕ} {s : ℕ → G} (h : Relations n s)
    {i j k : ℕ} (hi : i + 1 < j) (hbound : j+k ≤ n) :
    down s j k * s i = s i * down s j k := by
  induction k generalizing j with
  | zero => simp
  | succ k ih =>
    rw [down_succ, mul_assoc, ← h.distant i j (by omega) (by omega) hi,
      ← mul_assoc, ih (by omega) (by omega), mul_assoc]

theorem down_push_above {n : ℕ} {s : ℕ → G} (h : Relations n s)
    {i j k : ℕ} (hji : j < i) (hik : i < j+k) (hbound : j+k ≤ n) :
    down s j k * s i = s (i-1) * down s j k := by
  induction k generalizing j with
  | zero => omega
  | succ k ih =>
    by_cases heq : i = j+1
    · subst i
      cases k with
      | zero => omega
      | succ k =>
        simp only [down_succ]
        have hb := h.braid j (by omega)
        have hc := down_commute_below h (i := j) (j := j+1+1) (k := k)
          (by omega) (by omega)
        simp only [Nat.add_sub_cancel]
        calc
          down s (j+1+1) k * s (j+1) * s j * s (j+1) =
              down s (j+1+1) k * (s (j+1) * s j * s (j+1)) := by simp [mul_assoc]
          _ = down s (j+1+1) k * (s j * s (j+1) * s j) := by rw [hb]
          _ = s j * (down s (j+1+1) k * s (j+1) * s j) := by rw [← mul_assoc, ← mul_assoc, hc]; simp [mul_assoc]
    · rw [down_succ, mul_assoc, h.distant j i (by omega) (by omega) (by omega),
        ← mul_assoc, ih (by omega) (by omega) (by omega), mul_assoc]

/-- The submonoid generated by the first `n` indexed elements. -/
def generated (s : ℕ → G) (n : ℕ) : Submonoid G :=
  Submonoid.closure {x | ∃ i < n, s i = x}

theorem generator_mem (s : ℕ → G) {i n : ℕ} (hi : i < n) :
    s i ∈ generated s n := Submonoid.subset_closure ⟨i, hi, rfl⟩

/-- The elementary coset normal form for a chain of adjacent transpositions. -/
theorem normal_form {n : ℕ} {s : ℕ → G} (h : Relations (n+1) s)
    {w : G} (hw : w ∈ generated s (n+1)) :
    ∃ u ∈ generated s n, ∃ j ≤ n+1, w = u * down s j (n+1-j) := by
  induction hw using Submonoid.closure_induction_right with
  | one => exact ⟨1, one_mem _, n+1, le_rfl, by simp⟩
  | mul_right x hx y hy ih =>
    obtain ⟨i, hi, rfl⟩ := hy
    obtain ⟨u, hu, j, hj, rfl⟩ := ih
    rcases lt_trichotomy (i+1) j with hij | hij | hij
    · refine ⟨u * s i, mul_mem hu (generator_mem s (by omega)), j, hj, ?_⟩
      rw [mul_assoc, down_commute_below h hij (by omega), ← mul_assoc]
    · refine ⟨u, hu, i, by omega, ?_⟩
      have hlen : n+1-i = (n+1-j)+1 := by omega
      rw [hlen, down_succ, hij, mul_assoc]
    · by_cases heq : i = j
      · subst i
        refine ⟨u, hu, j+1, by omega, ?_⟩
        have hlen : n+1-j = (n+1-(j+1))+1 := by omega
        rw [hlen, down_succ, mul_assoc, mul_assoc, h.square j hi, mul_one]
      · refine ⟨u * s (i-1), mul_mem hu (generator_mem s (by omega)), j, hj, ?_⟩
        rw [mul_assoc, down_push_above h (by omega) (by omega) (by omega), ← mul_assoc]

end NormalForm

section Presentation

variable {G : Type*} [Monoid G]

/-- Extend a finite family by the identity outside its indexing range. -/
def extendFamily {n : ℕ} (s : Fin n → G) (i : ℕ) : G :=
  if hi : i < n then s ⟨i, hi⟩ else 1

@[simp] theorem extendFamily_apply {n : ℕ} (s : Fin n → G) (i : Fin n) :
    extendFamily s i = s i := by simp [extendFamily]

theorem liftable_of_relations {n : ℕ} {s : Fin n → G}
    (h : Relations n (extendFamily s)) : CoxeterMatrix.IsLiftable (CoxeterMatrix.Aₙ n) s := by
  intro i j
  have hsi : s i * s i = 1 := by simpa using h.square i i.isLt
  have hsj : s j * s j = 1 := by simpa using h.square j j.isLt
  simp only [CoxeterMatrix.Aₙ, Matrix.of_apply]
  split_ifs with heq hadj
  · subst j
    simpa using hsi
  · have hb : s i * s j * s i = s j * s i * s j := by
      rcases hadj with hadj | hadj
      · have hb := h.braid j (by omega)
        have he : extendFamily s (j.val+1) = s i := by rw [hadj]; simp
        simpa only [extendFamily_apply, he] using hb.symm
      · have hb := h.braid i (by omega)
        have he : extendFamily s (i.val+1) = s j := by rw [hadj]; simp
        simpa only [extendFamily_apply, he] using hb
    calc
      (s i * s j)^3 = s i * (s j * s i * s j) * s i * s j := by simp [pow_succ, mul_assoc]
      _ = s i * (s i * s j * s i) * s i * s j := by rw [← hb]
      _ = (s i * s i) * s j * (s i * s i) * s j := by simp [mul_assoc]
      _ = 1 := by rw [hsi, one_mul, mul_one, hsj]
  · have hc : s i * s j = s j * s i := by
      have hn : i.val ≠ j.val := fun hij => heq (Fin.ext hij)
      rcases lt_trichotomy i.val j.val with hij | hij | hij
      · simpa using h.distant i j i.isLt j.isLt (by omega)
      · exact False.elim (hn hij)
      · simpa using (h.distant j i j.isLt i.isLt (by omega)).symm
    calc
      (s i * s j)^2 = s i * (s j * s i) * s j := by simp [pow_two, mul_assoc]
      _ = s i * (s i * s j) * s j := by rw [← hc]
      _ = (s i * s i) * (s j * s j) := by simp [mul_assoc]
      _ = 1 := by rw [hsi, hsj, one_mul]

/-- The adjacent transposition with zero-based index `i`. -/
def adjacent (n : ℕ) (i : Fin n) : Equiv.Perm (Fin (n+1)) :=
  Equiv.swap i.castSucc i.succ

theorem adjacent_relations (n : ℕ) : Relations n (extendFamily (adjacent n)) := by
  constructor
  · intro i hi
    simp [extendFamily, hi, adjacent]
  · intro i j hi hj hij
    simp only [extendFamily, dif_pos hi, dif_pos hj, adjacent]
    rw [Equiv.swap_mul_eq_mul_swap]
    congr 2
    · exact Equiv.swap_apply_of_ne_of_ne (by intro he; have := congrArg Fin.val he; simp at this; omega)
        (by intro he; have := congrArg Fin.val he; simp at this; omega)
    · exact Equiv.swap_apply_of_ne_of_ne (by intro he; have := congrArg Fin.val he; simp at this; omega)
        (by intro he; have := congrArg Fin.val he; simp at this; omega)
  · intro i hi
    have hi' : i < n := by omega
    simp only [extendFamily, dif_pos hi, dif_pos hi', adjacent]
    let a : Fin (n+1) := ⟨i, by omega⟩
    let b : Fin (n+1) := ⟨i+1, by omega⟩
    let c : Fin (n+1) := ⟨i+2, by omega⟩
    change Equiv.swap a b * Equiv.swap b c * Equiv.swap a b =
      Equiv.swap b c * Equiv.swap a b * Equiv.swap b c
    have hab : a ≠ b := by intro he; have := congrArg Fin.val he; dsimp [a,b] at this; omega
    have hac : a ≠ c := by intro he; have := congrArg Fin.val he; dsimp [a,c] at this; omega
    have hbc : b ≠ c := by intro he; have := congrArg Fin.val he; dsimp [b,c] at this; omega
    rw [Equiv.swap_mul_swap_mul_swap hab hac]
    rw [Equiv.swap_comm a b, Equiv.swap_comm b c,
      Equiv.swap_mul_swap_mul_swap hbc.symm hac.symm]
    exact Equiv.swap_comm a c

/-- The abstract type-A presentation, before proving its identification with permutations. -/
abbrev AGroup (n : ℕ) := (CoxeterMatrix.Aₙ n).Group

abbrev system (n : ℕ) := (CoxeterMatrix.Aₙ n).toCoxeterSystem

abbrev simple (n : ℕ) := (system n).simple

theorem simple_relations (n : ℕ) : Relations n (extendFamily (simple n)) := by
  constructor
  · intro i hi
    simp only [extendFamily, dif_pos hi]
    exact (system n).simple_mul_simple_self _
  · intro i j hi hj hij
    let a : Fin n := ⟨i, hi⟩
    let b : Fin n := ⟨j, hj⟩
    have hab : a ≠ b := by intro he; have := congrArg Fin.val he; dsimp [a,b] at this; omega
    have hm : (CoxeterMatrix.Aₙ n) a b = 2 := by simp [CoxeterMatrix.Aₙ, hab, a,b]; omega
    have hm' : (CoxeterMatrix.Aₙ n) b a = 2 := by rw [CoxeterMatrix.symmetric]; exact hm
    have hb := (system n).wordProd_braidWord_eq a b
    simpa [CoxeterSystem.braidWord, hm, hm', CoxeterSystem.alternatingWord,
      CoxeterSystem.wordProd, extendFamily, hi, hj, a, b] using hb
  · intro i hi
    have hi' : i < n := by omega
    let a : Fin n := ⟨i, hi'⟩
    let b : Fin n := ⟨i+1, hi⟩
    have hab : a ≠ b := by intro he; have := congrArg Fin.val he; dsimp [a,b] at this; omega
    have hm : (CoxeterMatrix.Aₙ n) a b = 3 := by simp [CoxeterMatrix.Aₙ, hab, a,b]
    have hm' : (CoxeterMatrix.Aₙ n) b a = 3 := by rw [CoxeterMatrix.symmetric]; exact hm
    have hb := (system n).wordProd_braidWord_eq a b
    simpa [CoxeterSystem.braidWord, hm, hm', CoxeterSystem.alternatingWord,
      CoxeterSystem.wordProd, extendFamily, hi, hi', a, b, mul_assoc] using hb.symm

/-- The map from the presentation to the actual symmetric group. -/
noncomputable def toPerm (n : ℕ) : AGroup n →* Equiv.Perm (Fin (n+1)) :=
  (system n).lift ⟨adjacent n, liftable_of_relations (adjacent_relations n)⟩

@[simp] theorem toPerm_simple (n : ℕ) (i : Fin n) :
    toPerm n (simple n i) = adjacent n i :=
  (system n).lift_apply_simple _ i

theorem toPerm_surjective (n : ℕ) : Function.Surjective (toPerm n) := by
  have hh : Submonoid.closure (Set.range (adjacent n)) ≤ MonoidHom.mrange (toPerm n) := by
    rw [Submonoid.closure_le]
    rintro _ ⟨i, rfl⟩
    exact ⟨simple n i, toPerm_simple n i⟩
  have ht : Submonoid.closure (Set.range (adjacent n)) = ⊤ :=
    Equiv.Perm.mclosure_swap_castSucc_succ n
  rw [ht] at hh
  intro p
  exact hh (Submonoid.mem_top p)

theorem generated_simple_eq_top (n : ℕ) : generated (extendFamily (simple n)) n = ⊤ := by
  have he : {x | ∃ i < n, extendFamily (simple n) i = x} = Set.range (simple n) := by
    ext x
    constructor
    · rintro ⟨i, hi, rfl⟩
      exact ⟨⟨i,hi⟩, by simp [extendFamily,hi]⟩
    · rintro ⟨i,rfl⟩
      exact ⟨i,i.isLt, by simp⟩
  rw [generated, he]
  exact (system n).submonoid_closure_range_simple

/-- Inclusion of the presentation on the first `n` generators. -/
noncomputable def rankInclude (n : ℕ) : AGroup n →* AGroup (n+1) :=
  (system n).lift ⟨fun i => simple (n+1) i.castSucc, by
    intro i j
    have hm : (CoxeterMatrix.Aₙ n) i j =
        (CoxeterMatrix.Aₙ (n+1)) i.castSucc j.castSucc := by simp [CoxeterMatrix.Aₙ]
    rw [hm]
    exact (system (n+1)).simple_mul_simple_pow i.castSucc j.castSucc⟩

@[simp] theorem include_simple (n : ℕ) (i : Fin n) :
    rankInclude n (simple n i) = simple (n+1) i.castSucc :=
  (system n).lift_apply_simple _ i

theorem exists_include_of_generated {n : ℕ} {u : AGroup (n+1)}
    (hu : u ∈ generated (extendFamily (simple (n+1))) n) :
    ∃ y : AGroup n, rankInclude n y = u := by
  induction hu using Submonoid.closure_induction with
  | mem x hx =>
    obtain ⟨i, hi, rfl⟩ := hx
    refine ⟨simple n ⟨i, hi⟩, ?_⟩
    rw [include_simple]
    simp only [extendFamily, dif_pos (show i < n+1 by omega)]
    rfl
  | one => exact ⟨1, map_one _⟩
  | mul a b ha hb iha ihb =>
    obtain ⟨a', rfl⟩ := iha
    obtain ⟨b', rfl⟩ := ihb
    exact ⟨a'*b', map_mul _ _ _⟩

/-- The ordinary inclusion fixing the final point of a finite symmetric group. -/
noncomputable def permInclude (n : ℕ) :
    Equiv.Perm (Fin (n+1)) →* Equiv.Perm (Fin (n+1+1)) :=
  Equiv.Perm.viaEmbeddingHom Fin.castSuccEmb

@[simp] theorem permInclude_castSucc (n : ℕ) (p : Equiv.Perm (Fin (n+1)))
    (x : Fin (n+1)) : permInclude n p x.castSucc = (p x).castSucc :=
  Equiv.Perm.viaEmbedding_apply _ _ _

@[simp] theorem permInclude_last (n : ℕ) (p : Equiv.Perm (Fin (n+1))) :
    permInclude n p (Fin.last (n+1)) = Fin.last (n+1) := by
  apply Equiv.Perm.viaEmbedding_apply_of_not_mem
  rintro ⟨x,hx⟩
  have hv := congrArg Fin.val hx
  simp at hv
  omega

theorem permInclude_adjacent (n : ℕ) (i : Fin n) :
    permInclude n (adjacent n i) = adjacent (n+1) i.castSucc := by
  apply Equiv.ext
  intro x
  induction x using Fin.lastCases with
  | last =>
    rw [permInclude_last]
    symm
    apply Equiv.swap_apply_of_ne_of_ne <;>
      intro he <;> have hh := congrArg Fin.val he <;> simp at hh <;> omega
  | cast x =>
    rw [permInclude_castSucc]
    change (Equiv.swap i.castSucc i.succ x).castSucc =
      Equiv.swap i.castSucc.castSucc i.castSucc.succ x.castSucc
    rw [Fin.succ_castSucc]
    exact Function.Injective.map_swap (Fin.castSucc_injective (n+1)) i.castSucc i.succ x

theorem toPerm_include (n : ℕ) (y : AGroup n) :
    toPerm (n+1) (rankInclude n y) = permInclude n (toPerm n y) := by
  have hh : (toPerm (n+1)).comp (rankInclude n) = (permInclude n).comp (toPerm n) := by
    apply (system n).ext_simple
    intro i
    simp only [MonoidHom.comp_apply, include_simple, toPerm_simple]
    exact (permInclude_adjacent n i).symm
  exact DFunLike.congr_fun hh y

theorem map_down {H : Type*} [Monoid H] (f : G →* H) (s : ℕ → G) (j k : ℕ) :
    f (down s j k) = down (fun i => f (s i)) j k := by
  induction k generalizing j with
  | zero => simp
  | succ k ih => simp only [down_succ, map_mul, ih]

@[simp] theorem toPerm_extendFamily (n i : ℕ) :
    toPerm n (extendFamily (simple n) i) = extendFamily (adjacent n) i := by
  by_cases hi : i < n
  · simp only [extendFamily, dif_pos hi, toPerm_simple]
  · simp only [extendFamily, dif_neg hi, map_one]

theorem toPerm_down (n j k : ℕ) :
    toPerm n (down (extendFamily (simple n)) j k) =
      down (extendFamily (adjacent n)) j k := by
  rw [map_down]
  congr 1
  funext i
  exact toPerm_extendFamily n i

/-- A descending string carries its lowest indexed point to its highest point. -/
theorem down_adjacent_apply (n j k : ℕ) (hk : j+k ≤ n) :
    down (extendFamily (adjacent n)) j k ⟨j, by omega⟩ = ⟨j+k, by omega⟩ := by
  induction k generalizing j with
  | zero => simp
  | succ k ih =>
    have hj : j < n := by omega
    rw [down_succ, Equiv.Perm.mul_apply]
    have hh : extendFamily (adjacent n) j (⟨j, by omega⟩ : Fin (n+1)) =
        ⟨j+1, by omega⟩ := by
      simp only [extendFamily, dif_pos hj, adjacent]
      exact Equiv.swap_apply_left _ _
    rw [hh]
    convert ih (j+1) (by omega) using 1
    congr 1
    omega

/-- Completeness of the adjacent-transposition relations: the permutation map has no kernel. -/
theorem toPerm_eq_one_imp : ∀ n (w : AGroup n), toPerm n w = 1 → w = 1 := by
  intro n
  induction n with
  | zero =>
    intro w hw
    exact (system 0).simple_induction_right (p := fun z => z = 1) w rfl
      (fun _ i => Fin.elim0 i)
  | succ n ih =>
    intro w hw
    have hmem : w ∈ generated (extendFamily (simple (n+1))) (n+1) := by
      rw [generated_simple_eq_top]
      exact Submonoid.mem_top _
    obtain ⟨u, hu, j, hj, hwform⟩ := normal_form (simple_relations (n+1)) hmem
    obtain ⟨y, rfl⟩ := exists_include_of_generated hu
    have hmap : permInclude n (toPerm n y) *
        down (extendFamily (adjacent (n+1))) j (n+1-j) = 1 := by
      simpa only [hwform, map_mul, toPerm_include, toPerm_down] using hw
    have hlast : down (extendFamily (adjacent (n+1))) j (n+1-j)
        ⟨j, by omega⟩ = Fin.last (n+1) := by
      convert down_adjacent_apply (n+1) j (n+1-j) (by omega) using 1
      apply Fin.ext
      simp only [Fin.val_last, Fin.val_mk]
      omega
    have hpoint := DFunLike.congr_fun hmap (⟨j, by omega⟩ : Fin (n+1+1))
    rw [Equiv.Perm.mul_apply, hlast, permInclude_last, Equiv.Perm.one_apply] at hpoint
    have hjeq : j = n+1 := by
      have hv := congrArg Fin.val hpoint
      simp only [Fin.val_last, Fin.val_mk] at hv
      exact hv.symm
    subst j
    simp only [Nat.sub_self, down_zero, mul_one] at hwform
    have hy : toPerm n y = 1 := by
      apply Equiv.Perm.viaEmbeddingHom_injective Fin.castSuccEmb
      change permInclude n (toPerm n y) = permInclude n 1
      rw [map_one, ← toPerm_include, ← hwform]
      exact hw
    rw [hwform, ih y hy, map_one]

theorem toPerm_injective (n : ℕ) : Function.Injective (toPerm n) :=
  (injective_iff_map_eq_one (toPerm n)).mpr (toPerm_eq_one_imp n)

/-- The rigorous identification of the type-A presentation with the actual symmetric group. -/
noncomputable def presentationEquiv (n : ℕ) :
    AGroup n ≃* Equiv.Perm (Fin (n+1)) :=
  MulEquiv.ofBijective (toPerm n) ⟨toPerm_injective n, toPerm_surjective n⟩

@[simp] theorem presentationEquiv_simple (n : ℕ) (i : Fin n) :
    presentationEquiv n (simple n i) = adjacent n i := toPerm_simple n i

/-- A type-A Coxeter system on genuine permutations, with the specified adjacent swaps. -/
noncomputable def symmetricSystem (n : ℕ) :
    CoxeterSystem (CoxeterMatrix.Aₙ n) (Equiv.Perm (Fin (n+1))) :=
  (system n).map (presentationEquiv n)

@[simp] theorem symmetricSystem_simple (n : ℕ) (i : Fin n) :
    (symmetricSystem n).simple i = adjacent n i := by
  rw [symmetricSystem, CoxeterSystem.map_simple, presentationEquiv_simple]

/-- Extend adjacent operators satisfying the three relations to the actual symmetric group.
The target need only be a monoid: the square relations already force every generator to be a unit.
-/
noncomputable def extension {n : ℕ} (s : Fin n → G)
    (h : Relations n (extendFamily s)) : Equiv.Perm (Fin (n+1)) →* G :=
  (symmetricSystem n).lift ⟨s, liftable_of_relations h⟩

@[simp] theorem extension_adjacent {n : ℕ} (s : Fin n → G)
    (h : Relations n (extendFamily s)) (i : Fin n) :
    extension s h (adjacent n i) = s i := by
  rw [← symmetricSystem_simple]
  exact (symmetricSystem n).lift_apply_simple _ i

/-- Existence and uniqueness of an actual symmetric-group representation from adjacent operators.
For `S₁₄`, specialize this theorem to `n = 13`.
-/
theorem existsUnique_extension {n : ℕ} (s : Fin n → G)
    (h : Relations n (extendFamily s)) :
    ∃! ρ : Equiv.Perm (Fin (n+1)) →* G, ∀ i, ρ (adjacent n i) = s i := by
  refine ⟨extension s h, extension_adjacent s h, ?_⟩
  intro ρ hρ
  apply (symmetricSystem n).ext_simple
  intro i
  rw [symmetricSystem_simple, hρ, extension_adjacent]

/-- A finite-index interface to the same theorem, exposing only the three ordinary relations. -/
theorem existsUnique_extension_of_relations {n : ℕ} (s : Fin n → G)
    (hsquare : ∀ i, s i * s i = 1)
    (hdistant : ∀ i j, i.val + 1 < j.val → s i * s j = s j * s i)
    (hbraid : ∀ i j, i.val + 1 = j.val →
      s i * s j * s i = s j * s i * s j) :
    ∃! ρ : Equiv.Perm (Fin (n+1)) →* G,
      ∀ i, ρ (Equiv.swap i.castSucc i.succ) = s i := by
  apply existsUnique_extension s
  constructor
  · intro i hi
    simpa only [extendFamily, dif_pos hi] using hsquare ⟨i,hi⟩
  · intro i j hi hj hij
    simpa only [extendFamily, dif_pos hi, dif_pos hj] using
      hdistant ⟨i,hi⟩ ⟨j,hj⟩ hij
  · intro i hi
    have hi' : i < n := by omega
    simpa only [extendFamily, dif_pos hi, dif_pos hi'] using
      hbraid ⟨i,hi'⟩ ⟨i+1,hi⟩ rfl

/-- The concrete fourteen-point specialization needed by the Young-representation project. -/
theorem existsUnique_symmetric14Representation (s : Fin 13 → G)
    (hsquare : ∀ i, s i * s i = 1)
    (hdistant : ∀ i j, i.val + 1 < j.val → s i * s j = s j * s i)
    (hbraid : ∀ i j, i.val + 1 = j.val →
      s i * s j * s i = s j * s i * s j) :
    ∃! ρ : Equiv.Perm (Fin 14) →* G,
      ∀ i, ρ (Equiv.swap i.castSucc i.succ) = s i :=
  existsUnique_extension_of_relations s hsquare hdistant hbraid

end Presentation

end Bridge.Young.CoxeterExtension
