# Conjecture 10.3, tightened: is rho(B) = 1 really the condition, or is it "one free direction"?
#
# The conjecture says s_lambda(mu_t u B) is a product of characters for every lambda IFF rho(B) = 1,
# where rho is the rank of the subgroup of C^x generated by B.  Every recorded test used B a SINGLE
# reciprocal pair.  Three checks:
#
#   A  INDEPENDENT CRITERION.  "Product of characters" implies every root lies on the unit circle.
#      The cyclotomic test is replaced by a numerical one -- compute the roots and measure |root| --
#      so that a failure cannot be an artefact of factoring over the wrong field.
#
#   B  A SECOND rank-one B.  If B = {z,1/z,z^2,1/z^2} fails, does B = {z,1/z,z^3,1/z^3} fail too?
#      One failure could be special; two make it the rule.
#
#   C  THE REPAIR.  Is the property instead equivalent to B being a single reciprocal pair, i.e. to
#      ONE free direction rather than to rank one?  The control B = {z,1/z} must pass throughout.
#
# Authors: Carles Marin + Claude (AI assistant).

def offcircle(v, tol=1e-9):
    """largest |  |root| - 1  | over the roots of v; 0 means every root is on the unit circle."""
    d = v.dict()
    lo = min(d.keys())
    S = PolynomialRing(QQ, 'x'); x = S.gen()
    P = sum(QQ(c) * x**(e - lo) for e, c in d.items())
    P = P // x**(P.valuation())
    if P.degree() == 0:
        return 0.0
    worst = 0.0
    for rt, _ in P.roots(ring=CC):
        worst = max(worst, abs(abs(rt) - 1))
    return worst

def run(B_exps, LMAX, tag):
    t = 2
    RK = LaurentPolynomialRing(QQ, 'z'); zz = RK.gen()
    A = [RK(1), RK(-1)] + [zz**e for e in B_exps]
    N = len(A)
    tested = onc = off = 0
    worstlist = []
    for size in range(1, LMAX + 1):
        for lam in Partitions(size, max_length=N):
            L = list(lam) + [0] * (N - len(lam))
            beta = [L[i] + N - 1 - i for i in range(N)]
            den = matrix(RK, N, N, lambda i, j: A[i] ** (N - 1 - j)).det()
            if den == 0:
                continue
            val = matrix(RK, N, N, lambda i, j: A[i] ** beta[j]).det() / den
            if val == 0:
                continue
            val = RK(val)
            tested += 1
            w = offcircle(val)
            if w < 1e-7:
                onc += 1
            else:
                off += 1
                if len(worstlist) < 4:
                    worstlist.append((tuple(lam), float(w)))
    print("=" * 74)
    print("%s :  B = z^%s,  N = %d" % (tag, str(B_exps), N))
    print("   nonzero values                     : %d" % tested)
    print("   every root on the unit circle      : %d" % onc)
    print("   SOME root off the unit circle      : %d" % off)
    for lam, w in worstlist:
        print("      lam=%-12s max | |root|-1 | = %.4f" % (str(lam), w))
    return off

a = run([1, -1], 9, "CONTROL  one reciprocal pair, rho = 1")
b = run([1, -1, 2, -2], 8, "rho = 1, two coupled pairs (z, z^2)")
c = run([1, -1, 3, -3], 8, "rho = 1, two coupled pairs (z, z^3)")

print("")
print("=" * 74)
print("control off-circle: %d   (must be 0)" % a)
print("z,z^2  off-circle : %d" % b)
print("z,z^3  off-circle : %d" % c)
print("")
print("rank one is therefore %s the condition."
      % ("NOT" if (b or c) and not a else "consistent with being"))
