# Conjecture 10.3 (coupling rank), tested where the paper never tested it.
#
# The conjecture: with A = mu_t u B, B inversion-closed and disjoint from mu_t, and rho(B) the rank
# of the subgroup of C^x generated by B, the value s_lambda(A) is a product of characters for every
# lambda if and only if rho(B) = 1.  All the recorded evidence is rho(B) = 1 with B a SINGLE pair
# (Theorem 3.1) and rho(B) >= 2 (D1).  The case the conjecture is actually about, rho(B) = 1 with B
# LARGER than one pair, was never run:
#
#     B = {z, 1/z, z^2, 1/z^2}  is inversion-closed, disjoint from mu_2 = {1,-1}, and has rho = 1.
#
# WHAT COUNTS AS "a product of characters" is the point, and counting irreducible polynomial factors
# is not it: chi_k is itself reducible.  What is true of any product of sl2 characters is that all
# of its roots are roots of unity -- it is a product of cyclotomic polynomials times a monomial.
# That is decidable, and the paper's own theorem is the control: at B = {z,1/z} every value is
# eps * chi * chi * chi and must pass.
#
# Authors: Carles Marin + Claude (AI assistant).

def cyclotomic_product(v):
    """is the Laurent polynomial v, up to a monomial and a constant, a product of cyclotomics?"""
    if v == 0:
        return True
    # a Laurent polynomial: shift by the lowest exponent to get an honest polynomial
    d = v.dict()
    lo = min(d.keys())
    S = PolynomialRing(v.base_ring(), 'x'); x = S.gen()
    P = sum(c * x**(e - lo) for e, c in d.items())
    try:
        fs = list(P.factor())
    except Exception:
        return None
    for f, _ in fs:
        if f.degree() == 0:
            continue
        g = f
        if g.degree() == 1 and g[0] == 0:      # a factor of z: a monomial
            continue
        try:
            if not g.is_cyclotomic():
                return False
        except Exception:
            return None
    return True

def run(t, B_exps, LMAX, tag):
    # over Q when the orbit is rational: a cyclotomic polynomial must stay irreducible for
    # is_cyclotomic to recognise it, and over Q(i) it would split into linear factors
    K = QQ if t == 2 else CyclotomicField(t)
    zeta = K(-1) if t == 2 else K.zeta(t)
    RK = LaurentPolynomialRing(K, 'z'); zz = RK.gen()
    A = [RK(zeta**k) for k in range(t)] + [zz**e for e in B_exps]
    N = len(A)
    good = bad = unknown = tested = 0
    firstbad = []
    for size in range(1, LMAX + 1):
        for lam in Partitions(size, max_length=N):
            L = list(lam) + [0] * (N - len(lam))
            beta = [L[i] + N - 1 - i for i in range(N)]
            den = matrix(RK, N, N, lambda i, j: A[i] ** (N - 1 - j)).det()
            if den == 0:
                continue
            val = matrix(RK, N, N, lambda i, j: A[i] ** beta[j]).det() / den
            if val == 0:
                continue
            val = RK(val)          # the quotient is exact: s_lambda is a Laurent polynomial
            tested += 1
            r = cyclotomic_product(val)
            if r is True:
                good += 1
            elif r is False:
                bad += 1
                if len(firstbad) < 5:
                    firstbad.append((tuple(lam), str(val)[:60]))
            else:
                unknown += 1
    print("=" * 74)
    print("%s :  t = %d,  B = z^%s,  N = %d,  excess = %d" % (tag, t, str(B_exps), N, N - t))
    print("   nonzero values tested            : %d" % tested)
    print("   all roots are roots of unity     : %d" % good)
    print("   NOT a product of characters      : %d" % bad)
    print("   undecided                        : %d" % unknown)
    for lam, v in firstbad:
        print("      lam=%-14s value = %s ..." % (str(lam), v))

run(2, [1, -1], 9, "CONTROL, the paper's own case")
run(2, [1, -1, 2, -2], 8, "NEVER TESTED, rho(B) = 1 with B larger")
