#!/usr/bin/env python3
"""ff_mixed_gap_products_2.py

Changelog (reverse chronological):
  2026-09-16  Created.  Follow-up to ff_mixed_gap_products.py (open problem 5,
              article 2).  Hardens and extends its findings:
              (1) BRUTE-FORCE confirmation (direct sumset enumeration, no
                  transfer matrices) of the two headline witnesses:
                  - improper permutation-invariance failure, n = 2, r = 4,
                    gap orders (0,0,1)/(0,1,0)/(1,0,0) -> 96/111/96;
                  - proper reversal failure, n = 3, r = 3, gaps (0,1) vs
                    (1,0) -> 45 vs 51.
              (2) EXACT (Fraction arithmetic) dimension of the unital algebra
                  generated by {T(0),...,T(n+1)} -- the float-rank run said
                  full at n = 2,3 but proper at n = 4 (33/36), n = 5 (42/49);
                  entries of long words reach 1e8, so tol-1e-6 ranks are
                  suspect.  Also the exact commutant dimension.
              (3) Arrangement patterns, r = 4, 5: which ordering of a gap
                  multiset maximizes/minimizes the count.  Hypothesis from the
                  n=2 witness: large gaps central -> max, large gaps at the
                  ends -> min.
              (4) Balancing moves at fixed gap sum, r = 3, sorted pairs,
                  improper AND proper: g(a,b) <= g(a+1,b-1) when a < b-1?
              (5) Two-dimensional log-supermodularity test of g(a,b), r = 3.
              (6) Log-concavity of the Perron-root sequence lambda(delta),
                  n = 2..8, both variants (floats, tol 1e-9, ratios printed).

Run:  python3 code/oneoff/ff_mixed_gap_products_2.py
"""

import sys
import os
from fractions import Fraction
from itertools import combinations_with_replacement, permutations

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
from linusson_ff_counting import (A_from_linusson, restrict_proper,
                                  transfer_matrix, ff_count,
                                  ff_count_bruteforce)

import numpy as np


def mats_for(n, proper=False):
    A = A_from_linusson(n)
    if proper:
        A = restrict_proper(A)
    Ts = {d: transfer_matrix(A, d, n) for d in range(0, n + 4)}
    u = [sum(row) for row in A]
    return A, Ts, u


def count_from_word(u, Ts, gaps):
    v = u[:]
    R = len(u)
    for g in gaps:
        T = Ts[g]
        v = [sum(v[a] * T[a][b] for a in range(R)) for b in range(R)]
    return sum(v)


def matmul(X, Y):
    K, C = len(Y), len(Y[0])
    return [[sum(X[i][k] * Y[k][j] for k in range(K)) for j in range(C)]
            for i in range(len(X))]


def section1_bruteforce_witnesses():
    print("== (1) brute-force confirmation of headline witnesses")
    print("   predicted sizes: n=2 r=4 -> |F_2|^4 = 5^4 = 625 tuples;")
    print("   n=3 r=3 proper -> |S_3|^3 = 5^3 = 125 tuples.  Trivial.")
    # improper, n = 2: gaps (0,0,1) -> ds (0,0,0,1); (0,1,0) -> (0,0,1,1);
    # (1,0,0) -> (0,1,1,1)
    for gaps in [(0, 0, 1), (0, 1, 0), (1, 0, 0)]:
        ds = [0]
        for g in gaps:
            ds.append(ds[-1] + g)
        tm = ff_count(2, ds, False)
        bf = ff_count_bruteforce(2, ds, False)
        print("   improper n=2 gaps %s (d=%s): transfer %d, brute %d, %s"
              % (gaps, ds, tm, bf, "AGREE" if tm == bf else "MISMATCH"))
    # proper, n = 3: gaps (0,1) -> ds (0,0,1); (1,0) -> ds (0,1,1)
    for gaps in [(0, 1), (1, 0)]:
        ds = [0]
        for g in gaps:
            ds.append(ds[-1] + g)
        tm = ff_count(3, ds, True)
        bf = ff_count_bruteforce(3, ds, True)
        print("   proper   n=3 gaps %s (d=%s): transfer %d, brute %d, %s"
              % (gaps, ds, tm, bf, "AGREE" if tm == bf else "MISMATCH"))


class ExactSpan:
    """Incremental row-reduced basis over Fraction (exact rank)."""

    def __init__(self, dim):
        self.dim = dim
        self.rows = []      # reduced rows
        self.pivots = []    # pivot column of each row

    def add(self, vec):
        """Try to add vec (list of Fractions).  Returns True if independent."""
        v = list(vec)
        for row, p in zip(self.rows, self.pivots):
            if v[p] != 0:
                c = v[p] / row[p]
                v = [a - c * b for a, b in zip(v, row)]
        for j, a in enumerate(v):
            if a != 0:
                self.rows.append(v)
                self.pivots.append(j)
                return True
        return False

    @property
    def rank(self):
        return len(self.rows)


def section2_exact_algebra():
    print("== (2) exact algebra dimension and commutant, n = 2..5")
    for n in (2, 3, 4, 5):
        A, Ts, u = mats_for(n, False)
        R = n + 2
        gens = [[[Fraction(x) for x in row] for row in Ts[d]]
                for d in range(0, n + 2)]
        ident = [[Fraction(int(i == j)) for j in range(R)] for i in range(R)]
        span = ExactSpan(R * R)
        span.add([x for row in ident for x in row])
        basis_mats = [ident]
        frontier = [ident]
        while frontier:
            new_frontier = []
            for f in frontier:
                for g in gens:
                    cand = matmul(f, g)
                    if span.add([x for row in cand for x in row]):
                        basis_mats.append(cand)
                        new_frontier.append(cand)
            frontier = new_frontier
        dim = span.rank
        print("   n=%d: exact algebra dimension %d of %d %s"
              % (n, dim, R * R, "(FULL)" if dim == R * R else
                 "(PROPER SUBALGEBRA)"))
        # exact commutant: X with T X = X T for all generators.
        # Unknowns X[i][j], equations sum_k T[i][k]X[k][j] - X[i][k]T[k][j]=0.
        rowsys = ExactSpan(R * R)
        eqcount = 0
        for g in gens:
            for i in range(R):
                for j in range(R):
                    coef = [Fraction(0)] * (R * R)
                    for k in range(R):
                        coef[k * R + j] += g[i][k]
                        coef[i * R + k] -= g[k][j]
                    if rowsys.add(coef):
                        eqcount += 1
        print("        commutant dimension: %d (scalars = 1)"
              % (R * R - rowsys.rank))


def section3_arrangements():
    print("== (3) arrangement argmax/argmin patterns, r = 4 and 5, improper")
    hypothesis_ok = 0
    hypothesis_bad = []
    for n in range(2, 6):
        A, Ts, u = mats_for(n, False)
        for k in (3, 4):
            for gaps in combinations_with_replacement(range(0, n + 2), k):
                if len(set(gaps)) == 1:
                    continue
                vals = {p: count_from_word(u, Ts, list(p))
                        for p in set(permutations(gaps))}
                mx = max(vals.values())
                mn = min(vals.values())
                if mx == mn:
                    continue
                argmax = sorted(p for p, v in vals.items() if v == mx)
                argmin = sorted(p for p, v in vals.items() if v == mn)

                def unimodal(p):
                    # increases (weakly) then decreases (weakly)
                    top = p.index(max(p))
                    return (all(p[i] <= p[i + 1] for i in range(top)) and
                            all(p[i] >= p[i + 1] for i in range(top,
                                                                len(p) - 1)))

                def antiunimodal(p):
                    # decreases then increases (large values at the ends)
                    bot = p.index(min(p))
                    return (all(p[i] >= p[i + 1] for i in range(bot)) and
                            all(p[i] <= p[i + 1] for i in range(bot,
                                                                len(p) - 1)))

                ok = (any(unimodal(p) for p in argmax) and
                      any(antiunimodal(p) for p in argmin))
                if ok:
                    hypothesis_ok += 1
                else:
                    hypothesis_bad.append((n, gaps, argmax, argmin))
    print("   'max at some unimodal arrangement, min at some anti-unimodal':"
          " holds for %d multisets, fails for %d"
          % (hypothesis_ok, len(hypothesis_bad)))
    for w in hypothesis_bad[:6]:
        n, gaps, amax, amin = w
        print("     FAILS n=%d multiset %s: argmax %s argmin %s"
              % (n, gaps, amax, amin))


def section4_balancing_moves():
    print("== (4) balancing moves at fixed gap sum, r = 3, sorted pairs")
    for proper in (False, True):
        tag = "proper" if proper else "improper"
        viol = 0
        checked = 0
        for n in range(2, 8):
            A, Ts, u = mats_for(n, proper)
            hi = n + 3
            for a in range(0, hi):
                for b in range(a + 2, hi):
                    # move (a,b) -> (a+1,b-1); for proper also test both orders
                    for order in ((a, b), (b, a)) if proper else ((a, b),):
                        checked += 1
                        moved = ((order[0] + 1, order[1] - 1)
                                 if order == (a, b) else (b - 1, a + 1))
                        g0 = count_from_word(u, Ts, list(order))
                        g1 = count_from_word(u, Ts, list(moved))
                        if g1 < g0:
                            viol += 1
                            if viol <= 6:
                                print("   %s BALANCING DECREASE n=%d %s->%s: "
                                      "%d -> %d" % (tag, n, order, moved,
                                                    g0, g1))
        print("   %s: %d balancing moves checked, %d decreases" %
              (tag, checked, viol))


def section5_log_supermodularity():
    print("== (5) 2-D log-(super/sub)modularity of g(a,b), r = 3, improper")
    superm = subm = neither = 0
    for n in range(2, 7):
        A, Ts, u = mats_for(n, False)
        hi = n + 3
        g = {(a, b): count_from_word(u, Ts, [a, b])
             for a in range(hi) for b in range(hi)}
        for a in range(hi - 1):
            for b in range(hi - 1):
                lhs = g[(a, b)] * g[(a + 1, b + 1)]
                rhs = g[(a + 1, b)] * g[(a, b + 1)]
                if lhs > rhs:
                    superm += 1
                elif lhs < rhs:
                    subm += 1
                else:
                    neither += 1
    print("   over n=2..6, all (a,b) squares: log-supermodular at %d, "
          "log-submodular at %d, equal at %d" % (superm, subm, neither))


def section6_perron_logconcavity():
    print("== (6) log-concavity of lambda(delta), n = 2..8 (floats)")
    for proper in (False, True):
        tag = "proper" if proper else "improper"
        bad = 0
        for n in range(2, 9):
            A, Ts, u = mats_for(n, proper)
            lam = []
            for d in range(0, n + 3):
                M = np.array(Ts[d], dtype=float)
                lam.append(max(abs(np.linalg.eigvals(M))))
            for d in range(1, len(lam) - 1):
                if lam[d] ** 2 < lam[d - 1] * lam[d + 1] - 1e-9:
                    bad += 1
                    print("   %s n=%d NOT log-concave at delta=%d: %s"
                          % (tag, n, d, lam[d - 1:d + 2]))
            if n <= 4:
                print("   %s n=%d lambda: %s"
                      % (tag, n, [round(float(x), 4) for x in lam]))
        print("   %s: log-concavity violations: %d" % (tag, bad))


if __name__ == "__main__":
    print("predicted sizes: brute-force sumsets 5^4 = 625 and 5^3 = 125 "
          "tuples; exact linear algebra in dimension <= 49; permutations of "
          "<= 5-element multisets, n <= 5.  All small.")
    section1_bruteforce_witnesses()
    section2_exact_algebra()
    section3_arrangements()
    section4_balancing_moves()
    section5_log_supermodularity()
    section6_perron_logconcavity()
    print("DONE.")
