#!/usr/bin/env python3
"""ff_mixed_gap_products.py

Changelog (reverse chronological):
  2026-09-16  Created.  Open problem 5 of article 2 (beyond constant gaps):
              experiments on products of distinct transfer matrices
              T(delta_2)...T(delta_r).  Sections:
              (1) NORMAL FORM: T(delta) = P^delta T(0) with P the saturating
                  one-step shift on the tp-index (row tau of T(delta) is row
                  max(tau-delta,-1) of T(0)), and u = e_{-1}^T T(0).  Hence
                  |FF(d)| = e_{-1}^T B P^{d2} B ... P^{dr} B 1 with B = T(0).
                  Checked exactly, both variants.
              (2) COMMUTATION census: which pairs T(a), T(b) commute
                  (exact integer arithmetic); ranks of commutators.
              (3) PERMUTATION invariance of the COUNT beyond the proved
                  gap-reversal: all orderings of gap multisets, r = 4, 5;
                  smallest witness of failure if any.  Also: does the PROPER
                  count share the (improper-proved) reversal invariance?
              (4) Monotonicity and log-concavity of |FF| in a single gap.
              (5) Balanced vs unbalanced gap vectors at fixed gap sum
                  (Schur-direction scouting), r = 3.
              (6) Spectral scouting: rho(T(a)T(b)) vs rho(T(a))rho(T(b)) and
                  vs the balanced product; numpy floats, tol 1e-9.
              (7) Dimension of the algebra generated by {T(0..n+1)}: if it is
                  the full matrix algebra, there is no common invariant
                  subspace (Burnside), killing simultaneous triangularization.
              (8) Factorization of the count across a saturated gap
                  (delta >= n+1 improper / n-1 proper).

Run:  python3 code/oneoff/ff_mixed_gap_products.py
      (from the project root; guardrail: systemd-run scope, MemoryMax=8G)
"""

import sys
import os
from itertools import combinations_with_replacement, permutations
from fractions import Fraction

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
from linusson_ff_counting import (F, A_from_linusson, restrict_proper,
                                  transfer_matrix, ff_count)

import numpy as np

NMAX = 8


def matmul(X, Y):
    R, C, K = len(X), len(Y[0]), len(Y)
    return [[sum(X[i][k] * Y[k][j] for k in range(K)) for j in range(C)]
            for i in range(R)]


def mats_for(n, proper=False):
    A = A_from_linusson(n)
    if proper:
        A = restrict_proper(A)
    Ts = {d: transfer_matrix(A, d, n) for d in range(0, n + 4)}
    u = [sum(row) for row in A]
    return A, Ts, u


def count_from_word(u, Ts, gaps):
    v = u[:]
    R = len(u)
    for g in gaps:
        T = Ts[g]
        v = [sum(v[a] * T[a][b] for a in range(R)) for b in range(R)]
    return sum(v)


def section1_normal_form():
    print("== (1) normal form T(delta) = P^delta T(0), u = e_{-1} T(0)")
    bad = 0
    for n in range(2, NMAX + 1):
        for proper in (False, True):
            A, Ts, u = mats_for(n, proper)
            B = Ts[0]
            R = n + 2  # index tau+1 = 0..n+1 for tau = -1..n
            for d in range(0, n + 4):
                # predicted: row (tau+1) of T(d) = row max(tau-d,-1)+1 of B
                pred = [B[max(t - d, 0)] for t in range(R)]
                if pred != Ts[d]:
                    bad += 1
                    print("   MISMATCH n=%d proper=%s delta=%d" % (n, proper, d))
            if u != B[0]:
                bad += 1
                print("   u MISMATCH n=%d proper=%s: u=%s B[0]=%s"
                      % (n, proper, u, B[0]))
    print("   checked n=2..%d, delta=0..n+3, both variants: %d mismatches"
          % (NMAX, bad))
    return bad


def section2_commutation():
    print("== (2) commutation census, exact")
    for n in range(2, NMAX + 1):
        for proper in (False, True):
            A, Ts, u = mats_for(n, proper)
            deltas = list(range(0, n + 3))
            commuting = []
            for a, b in combinations_with_replacement(deltas, 2):
                if a == b:
                    continue
                Xa, Xb = Ts[a], Ts[b]
                if matmul(Xa, Xb) == matmul(Xb, Xa):
                    commuting.append((a, b, Xa == Xb))
            nontrivial = [(a, b) for a, b, eq in commuting if not eq]
            equal = [(a, b) for a, b, eq in commuting if eq]
            print("   n=%d %s: commuting unequal pairs: %s ; equal-matrix "
                  "pairs: %s" % (n, "proper" if proper else "improper",
                                 nontrivial or "NONE", equal or "NONE"))
    # commutator ranks, improper, small n
    print("   commutator ranks [T(a),T(b)] (improper):")
    for n in (3, 4, 5):
        A, Ts, u = mats_for(n, False)
        for a in range(0, n + 2):
            row = []
            for b in range(0, n + 2):
                Xa, Xb = np.array(Ts[a], dtype=float), np.array(Ts[b], float)
                Cm = Xa @ Xb - Xb @ Xa
                row.append(np.linalg.matrix_rank(Cm, tol=1e-6))
            print("     n=%d a=%d: ranks over b=0..%d: %s" % (n, a, n + 1, row))


def section3_permutation_invariance():
    print("== (3) permutation invariance of the count")
    # (3a) proper REVERSAL first (open in the alexander note): r = 3, 4
    print("   (3a) proper-count reversal invariance:")
    bad = 0
    tested = 0
    for n in range(2, NMAX + 1):
        A, Ts, u = mats_for(n, True)
        for a in range(0, n + 2):
            for b in range(0, n + 2):
                if a >= b:
                    continue
                tested += 1
                x = count_from_word(u, Ts, [a, b])
                y = count_from_word(u, Ts, [b, a])
                if x != y:
                    bad += 1
                    if bad <= 5:
                        print("     REVERSAL FAILS (proper) n=%d gaps (%d,%d):"
                              " %d vs %d" % (n, a, b, x, y))
        # r = 4: reversal of (a,b,c) vs (c,b,a)
        for gaps in combinations_with_replacement(range(0, n + 2), 3):
            for perm in set(permutations(gaps)):
                rev = tuple(reversed(perm))
                if perm >= rev:
                    continue
                tested += 1
                x = count_from_word(u, Ts, list(perm))
                y = count_from_word(u, Ts, list(rev))
                if x != y:
                    bad += 1
                    if bad <= 5:
                        print("     REVERSAL FAILS (proper) n=%d gaps %s vs %s"
                              ": %d vs %d" % (n, perm, rev, x, y))
    print("     proper reversal: %d comparisons, %d failures" % (tested, bad))

    # (3b) full permutation invariance, r = 4 (3 gaps), improper + proper
    print("   (3b) all orderings of 3-gap multisets (r = 4):")
    for proper in (False, True):
        witness = None
        n_all_equal = 0
        n_multisets = 0
        for n in range(2, 7):
            A, Ts, u = mats_for(n, proper)
            for gaps in combinations_with_replacement(range(0, n + 2), 3):
                if len(set(gaps)) == 1:
                    continue
                n_multisets += 1
                vals = {}
                for perm in set(permutations(gaps)):
                    vals[perm] = count_from_word(u, Ts, list(perm))
                if len(set(vals.values())) == 1:
                    n_all_equal += 1
                elif witness is None:
                    witness = (n, gaps, vals)
        tag = "proper" if proper else "improper"
        print("     %s: %d/%d non-constant multisets permutation-invariant"
              % (tag, n_all_equal, n_multisets))
        if witness:
            n, gaps, vals = witness
            print("     %s smallest witness n=%d multiset %s:" % (tag, n, gaps))
            for perm in sorted(vals):
                print("        order %s -> %d" % (perm, vals[perm]))

    # (3c) r = 5 (4 gaps) spot check, improper, n = 2..4
    print("   (3c) r = 5 orderings, improper, n = 2..4:")
    for n in range(2, 5):
        A, Ts, u = mats_for(n, False)
        inv = tot = 0
        for gaps in combinations_with_replacement(range(0, n + 2), 4):
            if len(set(gaps)) == 1:
                continue
            tot += 1
            vals = {count_from_word(u, Ts, list(p))
                    for p in set(permutations(gaps))}
            if len(vals) == 1:
                inv += 1
        print("     n=%d: %d/%d multisets fully invariant" % (n, inv, tot))


def section4_monotone_logconcave():
    print("== (4) monotonicity + log-concavity in a single gap")
    for proper in (False, True):
        tag = "proper" if proper else "improper"
        mono_bad = lc_bad = 0
        lc_witnesses = []
        for n in range(2, NMAX + 1):
            A, Ts, u = mats_for(n, proper)
            thr = (n - 1) if proper else (n + 1)
            # r = 2: g(delta)
            g = [count_from_word(u, Ts, [d]) for d in range(0, n + 4)]
            for d in range(1, len(g)):
                if g[d] < g[d - 1]:
                    mono_bad += 1
                if d <= thr and g[d] == g[d - 1]:
                    mono_bad += 1
                    print("   %s n=%d: NOT strictly increasing at delta=%d"
                          % (tag, n, d))
            for d in range(1, len(g) - 1):
                if g[d] * g[d] < g[d - 1] * g[d + 1]:
                    lc_bad += 1
                    lc_witnesses.append((tag, n, "r2", d, g[d - 1], g[d], g[d + 1]))
            if n <= 6:
                # r = 3 slices: vary second gap with first fixed
                for a in range(0, n + 2):
                    h = [count_from_word(u, Ts, [a, d]) for d in range(0, n + 4)]
                    for d in range(1, len(h) - 1):
                        if h[d] * h[d] < h[d - 1] * h[d + 1]:
                            lc_bad += 1
                            lc_witnesses.append((tag, n, "r3,a=%d" % a, d,
                                                 h[d - 1], h[d], h[d + 1]))
        print("   %s: monotonicity violations: %d; log-concavity violations:"
              " %d" % (tag, mono_bad, lc_bad))
        for w in lc_witnesses[:8]:
            print("      LC witness: %s" % (w,))


def section5_fixed_sum():
    print("== (5) fixed gap sum, r = 3: g(a,b) with a+b = sigma")
    for n in (3, 4, 5, 6):
        A, Ts, u = mats_for(n, False)
        print("   n=%d (improper), threshold n+1=%d:" % (n, n + 1))
        for sigma in range(0, 2 * (n + 1) + 1):
            vals = []
            for a in range(0, sigma + 1):
                b = sigma - a
                if a > n + 3 or b > n + 3:
                    continue
                vals.append(((a, b), count_from_word(u, Ts, [a, b])))
            # by reversal, (a,b) and (b,a) agree; print a <= b half
            half = [(ab, v) for ab, v in vals if ab[0] <= ab[1]]
            ordered = sorted(half, key=lambda t: t[1])
            direction = ("balanced-max" if ordered[-1][0][0] == sigma // 2
                         else ("extreme-max" if ordered[-1][0][0] == 0
                               else "interior-max"))
            print("     sigma=%2d: %s   [%s]"
                  % (sigma, ", ".join("%s:%d" % (ab, v) for ab, v in half),
                     direction))


def section6_spectra():
    print("== (6) spectral scouting (numpy, tol 1e-9)")
    for n in (2, 3, 4, 5):
        A, Ts, u = mats_for(n, False)
        rho = {d: max(abs(np.linalg.eigvals(np.array(Ts[d], float))))
               for d in range(0, n + 3)}
        print("   n=%d Perron roots: %s"
              % (n, {d: round(float(r), 6) for d, r in rho.items()}))
        for a in range(0, n + 2):
            for b in range(a + 1, n + 2):
                Xa = np.array(Ts[a], float)
                Xb = np.array(Ts[b], float)
                rab = max(abs(np.linalg.eigvals(Xa @ Xb)))
                prod = rho[a] * rho[b]
                rel = (rab - prod) / prod
                flag = ""
                if rab > prod + 1e-9:
                    flag = "  <-- rho(T(a)T(b)) > rho(T(a))rho(T(b))"
                # balanced comparison when a+b even
                bal = ""
                if (a + b) % 2 == 0:
                    m = (a + b) // 2
                    r2 = rho[m] ** 2
                    bal = " vs rho(T(%d))^2=%.6f (%s)" % (
                        m, r2, "mixed>bal" if rab > r2 + 1e-9 else
                        ("mixed<bal" if rab < r2 - 1e-9 else "equal"))
                print("     n=%d (a,b)=(%d,%d): rho(TaTb)=%.6f, "
                      "rho(Ta)rho(Tb)=%.6f, rel=%+.2e%s%s"
                      % (n, a, b, rab, prod, rel, bal, flag))


def section7_algebra_dimension():
    print("== (7) dimension of the algebra generated by {T(0),...,T(n+1)}")
    for n in (2, 3, 4, 5):
        A, Ts, u = mats_for(n, False)
        R = n + 2
        gens = [np.array(Ts[d], float) for d in range(0, n + 2)]
        basis = [np.eye(R)]
        # span-closure under right multiplication by generators
        def dim_of(mats):
            M = np.array([m.flatten() for m in mats])
            return np.linalg.matrix_rank(M, tol=1e-6)
        frontier = [np.eye(R)]
        cur = dim_of(basis)
        while True:
            new_frontier = []
            for f in frontier:
                for g in gens:
                    cand = f @ g
                    if dim_of(basis + [cand]) > dim_of(basis):
                        basis.append(cand)
                        new_frontier.append(cand)
            nd = dim_of(basis)
            if nd == cur or nd == R * R:
                cur = nd
                break
            cur = nd
            frontier = new_frontier
        print("   n=%d: algebra dimension %d of %d %s"
              % (n, cur, R * R,
                 "(FULL: irreducible, no common invariant subspace)"
                 if cur == R * R else "(PROPER SUBALGEBRA)"))


def section8_saturated_factorization():
    print("== (8) factorization across a saturated gap")
    bad = 0
    for n in range(2, 7):
        for proper in (False, True):
            thr = (n - 1) if proper else (n + 1)
            for left in ([0], [1], [0, 2], [1, 1]):
                for right in ([0], [2], [1, 0]):
                    gaps = left + [thr] + right
                    ds = [0]
                    for g in gaps:
                        ds.append(ds[-1] + g)
                    dl = [0]
                    for g in left:
                        dl.append(dl[-1] + g)
                    dr = [0]
                    for g in right:
                        dr.append(dr[-1] + g)
                    whole = ff_count(n, ds, proper)
                    parts = ff_count(n, dl, proper) * ff_count(n, dr, proper)
                    if whole != parts:
                        bad += 1
                        print("   FACTORIZATION FAILS n=%d proper=%s gaps=%s: "
                              "%d vs %d" % (n, proper, gaps, whole, parts))
    print("   checked n=2..6, both variants, 12 splits each: %d failures" % bad)


if __name__ == "__main__":
    print("predicted sizes: matrices are (n+2)x(n+2), n <= %d -> <= 10x10;"
          % NMAX)
    print("no family enumeration in this script; largest loop = permutations"
          " of 3-gap multisets over n<=6 (~120 multisets x 6 orders).")
    section1_normal_form()
    section2_commutation()
    section3_permutation_invariance()
    section4_monotone_logconcave()
    section5_fixed_sum()
    section6_spectra()
    section7_algebra_dimension()
    section8_saturated_factorization()
    print("DONE.")
