# Changelog (reverse chronological):
# 2026-07-31 21:31 - Claude-Code (agent-shell session, attached from Emacs): created this file.
#   Static-image companion to the interactive artifact (paramspace_n4_d1_visualization.html):
#   this Emacs (agent-shell attach, no xwidgets/webkit compiled in -- confirmed via
#   `system-configuration-features` -- so no live canvas can render in a buffer) can still display
#   a plain PNG inline, so this renders the same geometry (../runs/paramspace_n4_d1_mesh_geometry.json,
#   itself generated by parameter_space_n4d1_mesh.py) as a static matplotlib 3D plot instead.
#   Same two-hue scheme as the artifact (blue #2a78d6 generic, orange #eb6834 wall).

"""
Static matplotlib rendering of the n=4, d=1 parameter-space geometry (tetrahedron + the
a2*a4=a3^2 wall surface + sample points), for contexts that can't render the interactive
artifact (paramspace_n4_d1_visualization.html) -- e.g. inline display in a plain Emacs buffer
with no xwidgets/webkit support.

Usage: python3 parameter_space_n4d1_static_plot.py   (from the code/ directory)
"""

import json
import os

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

OUTDIR_RUNS = '../runs'
OUTDIR_ARTEFACTS = '../artefacts'

GENERIC_COLOR = '#2a78d6'
SPECIAL_COLOR = '#eb6834'


def render(elev=18, azim=35, outname='paramspace_n4_d1_static.png'):
    with open(os.path.join(OUTDIR_RUNS, 'paramspace_n4_d1_mesh_geometry.json')) as f:
        geom = json.load(f)

    fig = plt.figure(figsize=(9, 9), dpi=160)
    fig.patch.set_facecolor('#0f1520')
    ax = fig.add_subplot(111, projection='3d')
    ax.set_facecolor('#0f1520')

    tv = geom['tetra_vertices']
    for i, j in geom['tetra_edges']:
        xs = [tv[i][0], tv[j][0]]
        ys = [tv[i][1], tv[j][1]]
        zs = [tv[i][2], tv[j][2]]
        ax.plot(xs, ys, zs, color='#8fa0c0', linewidth=1.2, alpha=0.6)

    wv = geom['wall_vertices']
    tris = [[wv[a], wv[b], wv[c]] for a, b, c in geom['wall_triangles']]
    surf = Poly3DCollection(tris, facecolor=SPECIAL_COLOR, edgecolor='none', alpha=0.35)
    ax.add_collection3d(surf)

    gp = geom['generic_points']
    ax.scatter([p[0] for p in gp], [p[1] for p in gp], [p[2] for p in gp],
               s=4, color=GENERIC_COLOR, alpha=0.55, depthshade=True, label='generic (11 vertices)')

    sp = geom['special_points']
    ax.scatter([p[0] for p in sp], [p[1] for p in sp], [p[2] for p in sp],
               s=10, color=SPECIAL_COLOR, alpha=0.9, depthshade=True, label='wall a2a4=a3^2 (10 vertices)')

    axis_names = ['a1', 'a2', 'a3', 'a4']
    for i, name in enumerate(axis_names):
        x, y, z = tv[i]
        ax.text(x * 1.12, y * 1.12, z * 1.12, name, color='#eef2f8', fontsize=13, fontweight='bold')

    ax.set_axis_off()
    ax.view_init(elev=elev, azim=azim)
    ax.set_box_aspect([1, 1, 1])
    legend = ax.legend(loc='upper left', facecolor='#161d2b', edgecolor='#2a3548',
                        labelcolor='#eef2f8', fontsize=9, framealpha=0.9)
    ax.set_title('n=4, d=1 parameter space: one combinatorial type\nplus the a2a4=a3^2 wall',
                 color='#eef2f8', fontsize=12, pad=0)

    outpath = os.path.join(OUTDIR_ARTEFACTS, outname)
    fig.savefig(outpath, facecolor=fig.get_facecolor(), bbox_inches='tight')
    plt.close(fig)
    print(f'wrote {outpath}')
    return outpath


if __name__ == '__main__':
    render()
