# Changelog (reverse chronological):
# 2026-07-31 - Claude: created this file. Computes Sage face-lattice
#   statistics (f-vector, height, width, a battery of is_* structural
#   predicates) for R = angle(a) + shift^d(angle(a)), a=ones/kozlov, and
#   serializes them to human-readable JSON under ../runs/. Deliberately
#   excludes order dimension (NP-hard in general, too slow at these sizes --
#   an attempt on the n=3,d=1 case sat for minutes with no result) and
#   is_distributive (a genuine Sage bug: it calls .join_irreducibles()
#   internally, which raises AttributeError on lattices built via
#   Polyhedron.face_lattice(), as opposed to Poset/LatticePoset built
#   directly -- see LOGBOOK.md 2026-07-31 for the traceback). Every other
#   property is wrapped in a wall-clock timeout (SIGALRM-based) so one
#   slow/hanging predicate doesn't sink an entire run -- timed-out or
#   erroring properties are recorded as a "not computed" string rather than
#   failing the whole log.

"""
Face-lattice statistics for R = angle(a) + shift^d(angle(a)), serialized to
JSON logs under ../runs/.

Depends on right_angle_simplex.py (ones_vector, kozlov_vector,
right_angle_minkowski_sum) -- load that file first, or just load this one,
since it loads its dependency itself (see the load() call below, relative
to the code/ directory).

Usage (from the code/ directory):

    sage -c "load('face_lattice_stats.py'); save_run(3, 1, 'ones')"

or, to (re)generate the whole planned matrix:

    sage -c "load('face_lattice_stats.py'); save_all_runs()"
"""

import json
import os
import signal
import time

load('right_angle_simplex.py')


# Deliberately excluded, see the changelog comment above:
#   - 'is_distributive' (Sage bug: calls .join_irreducibles(), unavailable
#     on Polyhedron.face_lattice() objects)
#   - order dimension / .dimension() (NP-hard in general; too slow here)
FACE_LATTICE_PROPERTIES = [
    'is_graded',
    'is_ranked',
    'is_eulerian',
    'is_modular',
    'is_complemented',
    'is_atomic',
    'is_coatomic',
    'is_self_dual',
    'is_semidistributive',
    'is_join_semidistributive',
    'is_meet_semidistributive',
    'is_upper_semimodular',
    'is_lower_semimodular',
    'is_supersolvable',
    'is_planar',
]


class _Timeout(Exception):
    pass


def _time_limited(func, timeout):
    """
    Call func() with a wall-clock timeout (seconds, via SIGALRM -- Unix
    only, main thread only). Returns (True, result) on success, or
    (False, a human-readable "not computed" string) on timeout or any
    exception, so a single slow/broken property never kills the whole run.
    """
    def _handler(signum, frame):
        raise _Timeout()
    old_handler = signal.signal(signal.SIGALRM, _handler)
    signal.alarm(timeout)
    try:
        return True, func()
    except _Timeout:
        return False, f'not computed (timeout after {timeout}s)'
    except Exception as e:
        return False, f'not computed (error: {type(e).__name__}: {e})'
    finally:
        signal.alarm(0)
        signal.signal(signal.SIGALRM, old_handler)


def face_lattice_stats(n, d, a_name, timeout=30):
    """
    n, d: as in right_angle_minkowski_sum(a, [0, d])
    a_name: 'ones' or 'kozlov'
    timeout: per-property wall-clock limit in seconds

    Returns a JSON-serializable dict of face-lattice statistics for
    R = angle(a) + shift^d(angle(a)).
    """
    a = ones_vector(n) if a_name == 'ones' else kozlov_vector(n)
    t0 = time.time()
    R = right_angle_minkowski_sum(a, [0, d])
    FL = R.face_lattice()

    stats = {
        '_description': (
            f'Face-lattice statistics for R = angle(a) + shift^{d}(angle(a)), '
            f'n={n}, d={d}, a={a_name}. Generated by code/face_lattice_stats.py '
            f'-- see that file and ../runs/description.md for methodology, '
            f'excluded properties, and the timeout convention.'
        ),
        'n': int(n),
        'd': int(d),
        'a_name': a_name,
        'a': [int(x) for x in a],
        'dim': int(R.dim()),
        'ambient_dim': int(R.ambient_dim()),
        'f_vector': [int(x) for x in R.f_vector()],
        'total_faces': int(sum(R.f_vector())),
        'excluded_properties': {
            'is_distributive': 'Sage bug -- calls .join_irreducibles(), '
                                'unavailable on this lattice construction',
            'order_dimension': 'NP-hard in general, too slow at this scale',
        },
        'timeout_seconds': int(timeout),
    }

    ok, val = _time_limited(FL.height, timeout)
    stats['height'] = int(val) if ok else val
    ok, val = _time_limited(FL.width, timeout)
    stats['width'] = int(val) if ok else val

    for prop in FACE_LATTICE_PROPERTIES:
        ok, val = _time_limited(getattr(FL, prop), timeout)
        stats[prop] = bool(val) if ok else val

    # NB: plain round() is shadowed by Sage's own round() in this namespace
    # (load()-ed code shares globals with the calling Sage session), which
    # returns an RDF element rather than a Python float -- not JSON
    # serializable, hence the explicit float() wrapper here.
    stats['wall_clock_seconds'] = float(round(time.time() - t0, 2))
    return stats


def save_run(n, d, a_name, timeout=30, outdir='../runs'):
    """
    Compute face_lattice_stats(n, d, a_name, timeout) and write it as
    human-readable (indented) JSON to ../runs/facelattice_n{n}_d{d}_{a_name}.json.
    Returns the path written.

    outdir defaults to '../runs', relative to the current working directory
    -- NOT to this file's location. (__file__ is not reliable here: Sage's
    load() does not set it to this script's path, it inherits whatever
    __file__ the calling session already had -- e.g. the sage binary's own
    path -- so an os.path.dirname(__file__) default silently writes files
    to the wrong place. Always run these functions from the code/
    directory, as documented in the module docstring above.)
    """
    os.makedirs(outdir, exist_ok=True)
    stats = face_lattice_stats(n, d, a_name, timeout)
    fname = f'facelattice_n{n}_d{d}_{a_name}.json'
    path = os.path.join(outdir, fname)
    with open(path, 'w') as f:
        json.dump(stats, f, indent=2)
        f.write('\n')
    return path


def save_all_runs(timeout=30, outdir='../runs'):
    """
    Generate the full planned matrix: n=3,4; d=1,...,n-1; a in {ones, kozlov}.
    Returns the list of paths written.
    """
    paths = []
    for n in (3, 4):
        for d in range(1, n):
            for a_name in ('ones', 'kozlov'):
                paths.append(save_run(n, d, a_name, timeout, outdir))
    return paths
