#!/usr/bin/env python3
"""Build a review copy of the manuscript: text shifted left, ruled right margin.

Changelog (newest first):

2026-09-08  Created at Jan's request, for reading article 1 on paper with a pen. The text block is
            pushed left and a wide right margin is ruled with faint lines to write in.

            It works by post-processing the .tex that the Org export already produces, rather than
            by keeping a second Org file or a second set of headers. That matters: a duplicated
            source is a source that silently drifts, and this document has already been through one
            round of exactly that (three figure images generated by hand and never regenerable).
            The review copy is therefore a pure derivative -- delete it and nothing is lost.

Usage:
    make_review_copy.py [--tex FILE] [--out FILE] [--rule-spacing MM] [--no-build]
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

# A4 is 210mm x 297mm. The text block keeps a normal left margin and gives up its right-hand
# third; the rules live in that band, inset a few mm from the text and from the paper edge.
PREAMBLE = r"""
%% ---- review copy: added by code/make_review_copy.py, do not edit here ----
\usepackage[a4paper,left=18mm,right=72mm,top=22mm,bottom=22mm,marginparwidth=0pt]{geometry}
\usepackage{eso-pic}
\usepackage{tikz}
\AddToShipoutPictureBG{%
  \begin{tikzpicture}[remember picture,overlay]
    \foreach \k in {0,...,@NRULES@}{%
      \draw[black!22,line width=0.15pt]
        ([shift={(144mm,-22mm-\k*@SPACING@mm)}]current page.north west) --
        ([shift={(202mm,-22mm-\k*@SPACING@mm)}]current page.north west);
    }
  \end{tikzpicture}%
}
%% ---- end review copy block ----
"""


def make_review_tex(tex: Path, out: Path, spacing: float) -> None:
    src = tex.read_text(encoding="utf-8")
    if r"\begin{document}" not in src:
        raise SystemExit(f"{tex}: no \\begin{{document}}; is this the exported manuscript?")
    usable_height = 297 - 22 - 18          # top margin, and a little clear of the foot
    nrules = int(usable_height // spacing)
    # LaTeX comment characters make %-formatting unusable here, so substitute by name.
    block = PREAMBLE.replace("@NRULES@", str(nrules)).replace("@SPACING@", f"{spacing:g}")
    # Insert immediately before \begin{document} so it overrides anything the export set up.
    out.write_text(src.replace(r"\begin{document}", block + "\n" + r"\begin{document}", 1),
                   encoding="utf-8")


def build(tex: Path) -> None:
    if not shutil.which("xelatex"):
        raise SystemExit("xelatex not found")
    for _ in range(3):
        subprocess.run(["xelatex", "-interaction=nonstopmode", tex.name],
                       cwd=tex.parent, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for ext in (".aux", ".log", ".out", ".toc"):
        tex.with_suffix(ext).unlink(missing_ok=True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", type=Path,
                    default=Path("article/exterior-convex_article1_latest.tex"))
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--rule-spacing", type=float, default=8.0, help="mm between rules")
    ap.add_argument("--no-build", action="store_true")
    args = ap.parse_args()

    tex = args.tex
    if not tex.is_file():
        raise SystemExit(f"{tex}: not found (run the Org export first)")
    out = args.out or tex.with_name(tex.stem + "_reviewcopy.tex")

    make_review_tex(tex, out, args.rule_spacing)
    print(f"wrote {out}")
    if not args.no_build:
        build(out)
        pdf = out.with_suffix(".pdf")
        print(f"built {pdf}" if pdf.is_file() else "PDF build FAILED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
