#!/usr/bin/env python3
"""Rebuild EVERY central-projector order-15 witness; certify old separator.
Requires numpy, used only with arbitrary-precision Python integer objects.
Counts are freshly generated by the independent concrete-permutation routine.
"""
from audit import parts,chi,f,concrete_counts,cycle_type,concrete_extensions
from math import gcd
from pathlib import Path
import numpy as np
import json,time,sys

start=time.time(); ROOT=Path(__file__).parent
ps=parts(15); index={p:i for i,p in enumerate(ps)}
T=np.array([[chi(p,r) for r in ps] for p in ps],dtype=object)
bundle=Path(sys.argv[1]) if len(sys.argv)>1 else ROOT/'supplied_bundle'
dual=json.loads((bundle/'old_separator.json').read_text())
assert tuple(map(tuple,dual['partitions']))==ps
y=dual['dual_integer']; fs=[f(p) for p in ps]
fy=[a*b for a,b in zip(fs,y)]
rays=set(); zero=0; labels=0; minimum=None; groups=[]
for p in range(1,8):
    q=15-p; P,Q=parts(p),parts(q); ip={r:i for i,r in enumerate(P)}; iq={s:i for i,s in enumerate(Q)}
    TP=np.array([[chi(a,r) for r in P] for a in P],dtype=object)
    TQ=np.array([[chi(b,s) for s in Q] for b in Q],dtype=object)
    for k in range(1,p+1):
        counts=concrete_counts(p,q,k)
        D=np.zeros((len(P)*len(Q),len(ps)),dtype=object)
        for (r,s,t),w in counts.items(): D[ip[r]*len(Q)+iq[s],index[t]]=w
        H=(D@T.T).reshape(len(P),len(Q),len(ps))
        U=(TP@H.reshape(len(P),-1)).reshape(len(P),len(Q),len(ps))
        V=(TQ@U.transpose(1,0,2).reshape(len(Q),-1)).reshape(len(Q),len(P),len(ps)).transpose(1,0,2)
        for a in range(len(P)):
            for b in range(len(Q)):
                raw=tuple(int(v) for v in V[a,b,:]); labels+=1
                g=gcd(*raw)
                if not g: zero+=1;continue
                row=tuple(v//g for v in raw)
                assert sum(v*d for v,d in zip(row,fs))==0
                pair=sum(v*t for v,t in zip(row,fy)); assert pair>=0,(P[a],Q[b],k,pair)
                minimum=pair if minimum is None else min(minimum,pair)
                rays.add(row)
        groups.append([p,q,k,len(P)*len(Q)])
        cycle_type.cache_clear(); concrete_extensions.cache_clear()
        print(f'PASS: full central group ({p},{q}; k={k}), {len(P)*len(Q)} labels',flush=True)
assert labels==8112 and zero==1310 and len(rays)==5398 and minimum==98
assert y[index[(15,)]]==9700 and y[index[(3,)*5]]==10000
assert min(y)>=0 and y[index[(1,)*15]]==0
assert all(y[index[(15,)]]>=yy for p,yy in zip(ps,y) if p!=(3,)*5)
report={'status':'PASS','labels':labels,'zero_labels':zero,'distinct_nonzero_rays':len(rays),
        'minimum_primitive_raw_separator_pairing':minimum,'target_normalized_pairing':-300,
        'all_other_PDC_rays_nonnegative':True,'all_immanant_nonnegativity_rays_nonnegative':True,
        'all_Schur_lower_bound_rays_nonnegative':True,'groups':groups,'elapsed_seconds':time.time()-start}
(ROOT/'cone_results.json').write_text(json.dumps(report,indent=2))
print(json.dumps(report,indent=2),flush=True)
